### ISSUE TITLE
Unable to run on crobtab bash script

### ISSUE THREAD

**Issue by martinorob** [BlueM/cliclick#103]
Hi,
I’m having issues on running cliclick trough a bash script on crontab.
The only way is to call it with osascript calling with terminal

osascript “tell application terminal to launch click.sh”

If i put click.sh on crontab it doesn’t works.

I have cliclick and click.sh and crontab and bash on permission allowed on control panel of Catalina.

May someone help me?
Thanks

**Comment by BlueM** [comment]
Some tasks can simply not be accomplished using crontab. (Other example: reading items from the keychain using `security`.)

You could try using a Launch Agent – which simply means writing a PList (XML) file. You should be able to find examples and documentation on the web.

**Comment by martinorob** [comment]
Thanks @BlueM but i think that there is no way to run launch agent every 4 hour (like crontab)

**Comment by martinorob** [comment]
Wrong.
https://www.splinter.com.au/using-launchd-to-run-a-script-every-5-mins-on/

I’ll give it a try

**Comment by martinorob** [comment]
Works like a charm.
I’ve used this to create a plist like a cron job with this
http://launched.zerowidth.com/plists

Thanks @BlueM for the hint
