### ISSUE TITLE
How to get '%' (instead of '5') when shift is already pressed?

### ISSUE THREAD

**Issue by mhofert** [BlueM/cliclick#108]
Hi,

I try to trigger screen recording on macOS 10.15.6 (Catalina) by pressing 'cmd-shift-%' (or 'cmd-shift-5'). 
When using 
    
    cliclick kd:cmd,shift kp:num-5

all I see is that a 5 is printed to the terminal. I assume, but not sure here, that I rather want to press '%' than '5' (even if it's the same key) since shift has already been pressed. How can this be done/specified?

Thanks & cheers,
M

**Comment by BlueM** [comment]
It should work using `cliclick kd:cmd,shift t:5` (`t` for `type`).

**Comment by mhofert** [comment]
... and that does work, thanks! That would be a nice example to have on `cliclick -h` somewhere.
