### ISSUE TITLE
keyboard input for question mark

### ISSUE THREAD

**Issue by lavinnyv** [BlueM/cliclick#110]
trying to figure out what the kp for "?" is. i've tried question, question-mark and even tried to get it to work with t:?. i've had no luck. has anyone out there been able to send "?" over cliclick?

**Comment by BlueM** [comment]
It should work with `t:?`:

`cliclick 't:?'`

If that doesn’t work for you: which keyboard layout are you using?

**Comment by lavinnyv** [comment]
i'm using an english keyboard on a mac.

but i'm sending cliclick over ssh to another mac.

i'm not near my project to show the error code, but i will post it as soon as i get to that computer.

**Comment by lavinnyv** [comment]
i'm in america using a mac, but trying to send the cliclick remotely. 
the app i'm using is royal tsx.

here is what i get when i try to send "?" through royal

home@mbpro-2015 ~ % cliclick t:3
home@mbpro-2015 ~ % cliclick “t:?”
zsh: no matches found: “t:?”
home@mbpro-2015 ~ % cliclick “t:?”
zsh: no matches found: “t:?”
home@mbpro-2015 ~ % cliclick t:?
zsh: no matches found: t:?
home@mbpro-2015 ~ %

sending of almost every other key works fine. almost being, i just did a 
test of sending "/" because it's the lower key of the same key and that 
had the same problem, but i have not gone through the full keyboard. but 
i use every letter and number key and i send a lot of combo keys with 
shift and control. shift arrow works, control 1, control a, etc. ? is 
about the only key press i use in my command set that i can't seem to 
get working.

i did do a test of just cliclick in terminal, with a delay and then hit 
a text file and it does type the "?", but theoretically it should be 
doing the same thing in royal tsx, that's just opening a terminal window 
for the commands.


here are screenshots of doing the same command in royal tsx and mac 
terminal, but what i just discovered is that in iterm2, the t:? doesn't 
work, but the "t:?" does. but it still doesn't in royal tsx, which the 
plugin to get the terminal to work in royal tsx is iterm2. so i'm not 
sure what might be going on.



SO... after all that, as i'm writing this i'm testing things out and had 
come across the "t:?" solution but then just reread your email below and 
found that all 3 methods of sending "?" worked in regular terminals, but 
not in royal tsx (t:?, "t:?", 't:?'). i was using a command task action 
to send this letter, but when i type it into royal tsx it does send the 
command over ssh, so i guess i'll have to talk to royal tsx about what 
could be going on here. i am able to command task every other letter 
with cliclick, so it's weird that just ? is tripping me up.

thanks for your time.
