### ISSUE TITLE
Run in Automator

### ISSUE THREAD

**Issue by jordan314** [BlueM/cliclick#114]
Thanks for this! It's already been useful for me.
I would like to run a script using cliclick with a keyboard shortcut, by registering it as a service. However when I try making an Automator Workflow or QuickAction, it runs but doesn't do anything. I also tried making an application bundle, but it runs and fails pretty silently. I do see "Service exited with abnormal code 127" in console.
I'm using catalina.
Here is my automator script, which types what's on the clipboard (it works when run from terminal):
````
#!/bin/bash
/usr/local/bin/cliclick t:"`/usr/bin/pbpaste`"
````

**Comment by Diegus83** [comment]
I'm not in Catalina to try this but I tried two ways that worked for me in Mojave to an extend. Depending on the clipboard content I get some error messages (it seems to have issues with spaces and other characters in the clipboard)

One is to use AppleScript to execute the bash script as a one liner. Add an "Run AppleScript" Action to your workflow and use this as the command:
`do shell script "/usr/local/bin/cliclick t:$(/usr/bin/pbpaste)"`

The second more direct way is to use a  "Run Shell Script" Action in Automator and shorten the command to:
/usr/local/bin/cliclick t:$(/usr/bin/pbpaste)


The other one would be to use Karabiner to create a complex key modification that runs the script, that way you don't need Automator at all.

**Comment by jordan314** [comment]
Thanks for this!
I'm unable to get it to run inside Automator or as a service using the "Run Shell Script" action. Did you choose a shell? I chose bash and chose workflow receives "no input". Are there any other settings I need to do? I'm saving it as a quick action.
When I use Run Applescript, it does work inside Automator, but doesn't work as a quick action / service.

**Comment by Diegus83** [comment]
I left the default shell (/bin/bash) and "no input" in "any application".
I also found that wrapping the command in quotes fixes the issue with the spaces:
`/usr/local/bin/cliclick t:"$(/usr/bin/pbpaste)"`

I'm thinking you may be having issues with some security settings. In System Preferences, under Securit & Privacy, Accessibility, I have Automator, Script Editor and Terminal in the "Allow the apps below to control your computer" list.

I never found Automator useful for anything, I prefer a combination of launchctl or karabiner and scripts, but when playing around with it in the past I got an error message about allowing the app to control the computer.

**Comment by jordan314** [comment]
Ohh your update 2 solved it for me! In my case I only need it for an app that I can't paste in. This solved my issue, thank you!!
