### ISSUE TITLE
how can I trigger cmd + h 

### ISSUE THREAD

**Issue by rmGFW** [BlueM/cliclick#115]
how can I trigger cmd + h 

I see the document , but it seems that it can't  . why ?

**Comment by BlueM** [comment]
Apart from the fact, that I don’t know what you mean by “document”, this executes ⌘H:

`cliclick kd:cmd t:h ku:cmd`

**Comment by rmGFW** [comment]
> Apart from the fact, that I don’t know what you mean by “document”, this executes ⌘H:
> 
> `cliclick kd:cmd t:h ku:cmd`

thanks ! it works!
🙏
