### ISSUE TITLE
Multiple monitors doesn't work when Primary display is lower or to the right

### ISSUE THREAD

**Issue by mOOky8D** [BlueM/cliclick#117]
The way that the mouse position reports in this case is that you'll have a negative number, and cliclick seems to interpret that as "0" so it has an upper/left bound at the origin of the primary display.

**Comment by mOOky8D** [comment]
Note, a workaround for this is to reposition the window to positive coordinates (using AppleScript in my case) prior to invoking the mouseclick action.

**Comment by BlueM** [comment]
From the built-in help:

> If you need to specify absolute negative values in case you have a setup with a second display arranged to the left of your main display, prefix the number with “=”, for instance “c:100,=-200”.

Haven’t tried that in years, but I haven’t heard any complaints that it wouldn’t work.

**Comment by mOOky8D** [comment]
Hah, I suppose I should have looked for that...RTFM.  I'll retract my issue, thanks for pointing that out!
