### ISSUE TITLE
How could I move to the negative coordinate?

### ISSUE THREAD

**Issue by nicholasguan** [BlueM/cliclick#121]
Hello! Developors.

I have two screen, and all x coordinate of the left screen is negative.
When I want to move mouse to the left screen by using `cliclick m:x,y`,
the mouse move relatively rather then move to the absolutely coordinate.

I'm trying to set the left screen is main screen to avoid the question,
but i prefer to set the right horizontal screen as main screen. 

Looking forward to your reply.

Thank you for that you read the issue.

**Comment by BlueM** [comment]
This has both been already answered in a previous issue (https://github.com/BlueM/cliclick/issues/117) and it’s also in the builtin help.

**Comment by nicholasguan** [comment]
Sorry. I didn't notice it had been duplicate. Thank you :)
