### ISSUE TITLE
Feature Request: Reading coordinates (both on click and on drag)

### ISSUE THREAD

**Issue by klueless-io** [BlueM/cliclick#122]
I came accross your project while trying to find a solution to reading the mouse coordinates so that I could automate the command line tool called screen capture.

My goal was to drag a rect (x,y,w,h) and store those coordinates so that I could re-caputure the same screen position multiple times.

It seems like a nice fit to add that feature to this project, but I understand if it is out of scope for you.

**Comment by BlueM** [comment]
`cliclick p` prints the current mouse position. So, if you move the mouse to your intended start position, run `cliclick p`, drag and after that, again invoke `cliclick p`, you have the coordinates you need. With some scripting, this could be used to automatically process and re-use the coodinates.

**Comment by klueless-io** [comment]
Thank you
