### ISSUE TITLE
zsh: killed     /usr/local/bin/cliclick

### ISSUE THREAD

**Issue by dstranathan** [BlueM/cliclick#123]
When I try to run cliclick on my M1 Mac running macOS 11.4 Big Sur I get an error in standard output that it was killed:

zsh: killed     /usr/local/bin/cliclick

macOS logs state "ASP: Security policy would not allow process: 1715, /usr/local/bin/cliclick"

**Comment by jlahijani** [comment]
I had this issue when downloading it from the author's website.  However cliclick works fine when installing via Homebrew.

**Comment by BlueM** [comment]
I assume you directly invoked cliclick in Terminal after downloading it? In that case it’s a quarantine issue, which you can resolve by opening the context menu (right-clicking the icon), choosing “Open” and then confirm that you are really, really sure you want to launch this extremely dangerous software. After that, it will work as expected.

**Comment by cashcowONE** [comment]
> I assume you directly invoked cliclick in Terminal after downloading it? In that case it’s a quarantine issue, which you can resolve by opening the context menu (right-clicking the icon), choosing “Open” and then confirm that you are really, really sure you want to launch this extremely dangerous software. After that, it will work as expected.

Giving it permission didn't work for me.
Installing via homebrew with "brew install cliclick" makes it work
