### ISSUE TITLE
How to combine CMD with single letter press

### ISSUE THREAD

**Issue by dedwarmo** [BlueM/cliclick#125]
How would I do a CMD-C if I wanted to simulate the keyboard shortcut for COPY?  I know it would start with kp:cmd.  How do I do a single letter keypress?

**Comment by BlueM** [comment]
It’s exactly like what you would do on a physical keyboard: hold down `cmd`, press `c`, release `cmd`:

`cliclick kd:cmd t:c ku:cmd`

**Comment by dedwarmo** [comment]
Thanks.  I’m away from my computer now but my mistake may have been not issuing the key up command.

**Comment by dedwarmo** [comment]
I added the key up command and it works perfectly.  Thanks!
