### ISSUE TITLE
shift doesnt seem to work

### ISSUE THREAD

**Issue by tgwaste** [BlueM/cliclick#126]
kd:shift kp:num-1 ku:shift

does not produce an '!'

**Comment by BlueM** [comment]
`num-1` is the key on the numpad. For a “!”, you should type the “regular” 1 key together with Shift (`cliclick kd:shift t:1 ku:shift`), or simply type the exclamation mark directly: `cliclick t:!`.

**Comment by tgwaste** [comment]
Sorry, I completely missed the option for ```cliclick t:```
