### ISSUE TITLE
Is there a parameter to control the speed of keyboard input？

### ISSUE THREAD

**Issue by zphj1987** [BlueM/cliclick#127]
i want control the speed of t:text   ,i see 
```bash
-e <easing> Set an easing factor for mouse movements.
```
but not find the type text speed parameter

**Comment by BlueM** [comment]
The delay between key presses is hardcoded. However, there are two ways to control timing:

* Option `-w` sets a wait time between commands in milliseconds, .e.g. `cliclick -w t:100 t:H t:e t:l t:l t:o`
* Using command `w:`, you can define a *single* waiting time: `cliclick t:H t:e w:200 t:l t:l t:o`.

However, both approaches won’t work when passing several characters to `t:`, for example `t:Hello`. Is cliclick too fast for you / your Mac?

**Comment by rirze** [comment]
If I can contribute, I'm looking for a simliar option as @zphj1987 because I find the default delay between key presses too *slow*...

I would love to find a way to make the typing faster.

**Comment by BlueM** [comment]
@rirze: feel free to add a PR. It should define an option which overrides the hardcoded value.

**Comment by zphj1987** [comment]
close
