### ISSUE TITLE
Old cliclick version

### ISSUE THREAD

**Issue by alin89c** [BlueM/cliclick#128]
Please include the cliclick version that worked on Mojave.
I've looked for it (see link below) and couldn't find it.
https://www.bluem.net/en

Thank you!

**Comment by KeygenLLC** [comment]
I can confirm this version works in Mojave.

I've tested using command modifiers, click drag, and auto-typing sentences. I'm using them in shell scripts and they also execute perfectly from within python scripts using `os.system()`.

Great tool and easy to use.
