### ISSUE TITLE
Way to hold right click?

### ISSUE THREAD

**Issue by Viridescence** [BlueM/cliclick#129]
Hello,
Is there currently a way to hold down a **right** click (so not using dd)? Either a click down, click up or a click duration parameter?

**Comment by BlueM** [comment]
That’s what `rc` (“right click”) is for:
`cliclick rc:123,456`

**Comment by logiota** [comment]
That is just a click not holding down until released with another command, the right click version of:
cliclick dd:. && sleep 2 && cliclick du:.

**Comment by logiota** [comment]
cliclick dd:. w:2000 du:. 
sorry
