### ISSUE TITLE
cliclick executes but nothing happens

### ISSUE THREAD

**Issue by farafao** [BlueM/cliclick#135]
I'm sorry but I'm unable to make it work.

When I run cliclick, e.g. with click and move actions, the command
executes but nothing happens.

I tried versions 5.0.1, 5.0, 4.0.1 
I'm Running Mojave on a macbook pro 2017

When I compile I get some warning messages
about deprecated symbols  (NSSystemDefined, NSStringPboardType)

Any hints? How do I debug?

thx

**Comment by dkbarto** [comment]
I attempted a dd:10,10 du:200,200 yet no selection was drawn. Clearly I'm missing something. Monterey 12.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Xcode 13.2 (13C90)

**Comment by BlueM** [comment]
@farafao: Terminal needs the permission to control the computer in System Preferences ➔ Security ➔ Accessibility. It sounds as if the permission has not been granted on your Mac.

**Comment by dkbarto** [comment]
My terminal has full control under Accessibility and the terminal still will go to the screen saver even though I repeat the move with clicliclk every minute run by a cron job.

**Comment by farafao** [comment]
@BlueM, it worked! Many thanks.
It's probably worth mentioning this requirement in the README and the documentation.

I'm closing this issue. 
Maybe @dkbarto you want to re-open or it's better to open a different issue?

**Comment by BlueM** [comment]
Info is added in the README

**Comment by BlueM** [comment]
@farafao: other than intended, you haven’t closed the issue, but as the question seems answered, I’ll doing that now.

@dkbarto: your issue is unrelated to the original question. If you want to create a new issue, please make sure you include all necessary information.
