### ISSUE TITLE
iTerm 2 prints color of macOS desktop wallpaper instead of overlying window

### ISSUE THREAD

**Issue by eomcb** [BlueM/cliclick#139]
Hello, when using iTerm 2 (with /bin/bash),
`cliclick cp:x,y`
prints the color of the macOS desktop wallpaper instead of the overlying window.

When using the default Apple Terminal app (/bin/bash), the same command prints the color of the window as expected.

What could be the cause for this and what setting could I set in iTerm2 to get the color at the given coordination of the overlying window?

Please cf. attached screenshot for more details.
![screenshot](https://user-images.githubusercontent.com/99484230/155178676-4a885941-7a3e-499b-9cf6-7550e98831c7.png)

Thank you in advance

**Comment by BlueM** [comment]
This can happen if iTerm does not have the permission to record the screen (but Terminal has). See the Security system preference.

**Comment by eomcb** [comment]
@BlueM, thank you for pointing me in the right direction, problem solved.
Best regards
