### ISSUE TITLE
Is there an equivalent to CLEARMODIFIERS in xdotool?

### ISSUE THREAD

**Issue by heywoodlh** [BlueM/cliclick#143]
I am trying to use a keyboard shortcut (with [skhd](https://github.com/koekeishiya/skhd)) `ctrl + [` to invoke `cliclick "c:."` (using `skhd`). It successfully executes `cliclick "c:."` but since I'm holding ctrl MacOS registers it as a right click.

In xdotool on Linux I can work around this using `CLEARMODIFIERS`. Is there anything comparable to that in cliclick?

**Comment by BlueM** [comment]
You could try to start with a “key up” command for `ctrl`: `cliclick ku:ctrl`. (So, together with your current command, the full command would become `cliclick ku:ctrl c:.`) But I have no idea whether this really works.
