### ISSUE TITLE
Cmd+H not working

### ISSUE THREAD

**Issue by leoheck** [BlueM/cliclick#145]
Hi, I am trying to hide the application that is on top, but it seems that the Cmd+H is not working

This is what I am trying to do:
```
cliclick kd:cmd kp:q
```

Is this right?

**Comment by BlueM** [comment]
Running command `kp:q` results in `Invalid key “q” given as argument to command “kp” …`, so this is obviously not correct. For simple characters, you have to use the “type” (`t`) command:

`cliclick kd:cmd t:h ku:cmd`

**Comment by leoheck** [comment]
Ah got it, I was thinking, somehow, the `t:` was used only on inputfields. This works flawlessly. Thank you. Maybe having this example on Readme would help other users too.
