### ISSUE TITLE
Cliclick is not working anymore 

### ISSUE THREAD

**Issue by leoheck** [BlueM/cliclick#155]
I am running a clean install of macOS 12.5 

Do I need to enable something in the settings to make it work? Nothing I do with cliclick works.

**Comment by leoheck** [comment]
Alright, this solved it.
https://github.com/BlueM/cliclick/commit/2098f2e11e54660b78de18e169b99e0c39b550e3

I could not find such thing in the Readme.

**Comment by BlueM** [comment]
It’s right at the top of the Readme: https://github.com/BlueM/cliclick/blame/master/README.markdown#L12
