### ISSUE TITLE
Case in first character in type (`t:`) command is not respected

### ISSUE THREAD

**Issue by cchase88** [BlueM/cliclick#157]
On macOS 12.4, the following command does not work as expected:

command: `cliclick t:'Hello World'`
expected output: `Hello World`
actual output: `hello World`

The first letter of the string to be typed is in lowercase even though it was specified as an uppercase char.

Likewise, attempting to type a single uppercase letter also results in a lowercase letter:

command: `cliclick t:H`
expected output: `H`
actual output: `h`

**Comment by BlueM** [comment]
Don’t have a 12.4 at hand, but I’m not able to reproduce this on 12.5.

**Comment by cchase88** [comment]
I realized I had left some crucial information out: I'm invoking the command via zsh within iTerm2. Running the command in the plain old terminal works as expected. I'm guessing this is a iTerm issue and not a cliclick issue.
