### ISSUE TITLE
Trouble sending to windowed application

### ISSUE THREAD

**Issue by HawkMan572** [BlueM/cliclick#166]
I'm trying to send key presses to a specific window but it does not work.

cliclick w:900 kp:arrow-up "-d /Users/xxxx/Library/Application Support/xxxx/xxxx”

**Comment by BlueM** [comment]
Cliclick doesn’t even know what a window is, it merely works with screen coordinates. In addition, `-d` does not expect a path as argument, see `cliclick -h`.
