### ISSUE TITLE
Key-list incomplete?

### ISSUE THREAD

**Issue by rwijtvliet** [BlueM/cliclick#173]
Is it possible to simulate key presses to other keys than the ones listed in the readme? 

Specifically, I'm looking for semicolon, apostrophe, comma, period.

**Comment by BlueM** [comment]
`cliclick 't:Semicolon ;  apostrophe ’  comma ,  period .'`

<img width="585" alt="Bildschirmfoto 2023-10-20 um 14 03 09" src="https://github.com/BlueM/cliclick/assets/1493457/e55dd1b8-4bf6-4c7a-a420-5e88797f11a6">


Doesn’t seem to be a problem

**Comment by rwijtvliet** [comment]
Ah, many thanks! Maybe they could be added to the readme?
