### ISSUE TITLE
Color print cp doesn't seem to work

### ISSUE THREAD

**Issue by Quust** [BlueM/cliclick#176]
cp command gives random color values, for example black gets value 27 20 14 (should be 0 0 0), white is 36 26 27 (should be 255 255 255) clean blue is 31 25 24 (should be 0 0 255). All other cliclick commands work. I'm using Apple Script on Sonoma 14.2.1

**Comment by DavidMBrown** [comment]
I am using cliclick 5.1 on macOS 14.3. cliclick's cp command returns the correct colors.

**Comment by BlueM** [comment]
@Quust: probably https://github.com/BlueM/cliclick/issues/139#issuecomment-1049525651

**Comment by Quust** [comment]
I works now, Thank you!
