### ISSUE TITLE
More “human-like” mouse movements (easing)

### ISSUE THREAD

**Issue by BlueM** [BlueM/cliclick#23]
For purposes such as scripting screencasts, where things like the movement of the mouse pointer should be perceivable (instead of the mouse jumping around the screen, which is what happens when using cliclick now), it would be nice to have mouse movement easing – probably cubic in/out easing.

This means that a whole series of mouse move events would have to be fired to emulate this.

Reminder: for calculating the easing, this would be sufficient:

``` objective-c
// Modeled after the piecewise cubic
// y = (1/2)((2x)^3)       ; [0, 0.5)
// y = (1/2)((2x-2)^3 + 2) ; [0.5, 1]
//
// Source: AHEasing, License: WTFPL
//
// Expects the [whatever action] to be split up into small steps represented
// by a float from 0 (start) to 1 (end). Method is to be called with the float
// and returns an "eased float" for it.
-(float)cubicEaseInOut:(float)p {
    if (p < 0.5) {
        return 4 * p * p * p;
    } else {
        float f = ((2 * p) - 2);
        return 0.5 * f * f * f + 1;
    }
}
```

**Comment by sixpetrov** [comment]
Hello. Is there a way to disable easing effect? I built the project, and I can't find option to disable easing.

I really need just move, I don't want to actually see how mouse is moved.

**Comment by BlueM** [comment]
Currently, there is no flag to disable easing, but there will be.

**Comment by BlueM** [comment]
https://www.bluem.net/en/news-and-beyond/cliclick-4-beta-2-released/

**Comment by sixpetrov** [comment]
Cool. Thank you. And thank you so much for sharing this project.  I started learning cocoa recently, and cliclick is super valuable resource.

I already changed few things. For example `cliclick p` will put coordinates to clipboard. So I can just paste it for mouse move or click. Pretty neat :)

Cheers

**Comment by BlueM** [comment]
You needn’t change the source – there’s `pbcopy` for that.

**Comment by sixpetrov** [comment]
True, but by default `cliclick p` outputs text also, I just need coordinates.
Also I remember Richard Stallman said once: the best way to learn is to take some open-source project and play with it :)

**Comment by BlueM** [comment]
Enter pipes: using …
`cliclick p | awk '{print $4}'`
… or …
`cliclick p | cut -d ' ' -f 4`
… or …
`cliclick p | perl -pe 's/^.*: //'`
… or one of numerous other tools you can modify the output however you need it – in this case everything except the coordinates would be dropped using any of the lines above.
