### ISSUE TITLE
Cannot read command file from stdin

### ISSUE THREAD

**Issue by alexchandel** [BlueM/cliclick#33]
When attempting to read commands from stdin, so that I could type them line by line into the terminal, by invoking cliclick as `cliclick -w 100 -f /dev/stdin` (and a few similar attempts), cliclick simply exits immediately and doesn't read from stdin/the terminal.

I'm doing this because I was trying to control a home theatre app with cliclick, by SSH'ing onto the machine running the home theatre app and having cliclick read from stdin and run commands. Individual commands like `cliclick -w 100 kp:return` work over SSH of course, but it's cumbersome to type that for every key, as opposed to typing like:
```bash
$ cliclick -w 100 -f /dev/stdin
h
j
k
l
:i
etc
```

This would allow me to interactively control said home theatre app just by typing into the terminal.

**Comment by BlueM** [comment]
With 0e0f400, you can read commands from stdin by passing `-` as filename to `-f`.

However, I’m not sure if that’s exactly what matches your requirements, as it will – just like reading a regular file – read stdin to the end, then execute the commands. But if you really need “key event streaming”, I guess it's fairly simply to write a small wrapper script which provides this and calls cliclick.
