### ISSUE TITLE
Add support for relative mouse movements

### ISSUE THREAD

**Issue by tennysonholloway** [BlueM/cliclick#34]
For example, say I need to move the mouse 50px down. Currently, I must find the current mouse position, then do some math to find the end mouse position. Preferably, we could just send the command `m:+0,+50`, to indicate a relative move of +0 on x and +50 on y. 

Love the utility!

**Comment by BlueM** [comment]
Quote from the built-in help:

“Whenever a command expects a pair of coordinates, you may provide relative values by prefixing the number with “+” or “-”. For example, “m:+50,+0” will move the mouse 50 pixels to the right.”
