### ISSUE TITLE
Does not work with Bluestacks

### ISSUE THREAD

**Issue by AmishP** [BlueM/cliclick#36]
Hi, I'm trying to use this with Bluestacks and it seems that the cursor is moved to the position but it does not stimulate the clicking. I have tried this with c, dc and tc. Is there a fix for this or a workaround that I could use? 

Thanks.

**Comment by jzzj** [comment]
Hi, I'm facing the same problem with Bluestacks, and i've been tried the AppleScript, it did't work either. Any advice will be appreciate.

**Comment by BlueM** [comment]
I don’t use Bluestacks – in fact, I hadn’t even heard of it before reading the ticket. Therefore, I do neither have an explanation or a workaround. Maybe someone else reading this has some idea?

**Comment by BlueM** [comment]
Someone else who also tried to control Bluestacks using cliclick pointed out to me that using the deprecated `CGPostMouseEvent()` call (which the Apple documentation calls a “a **low-level** mouse-button event”), clicking in Bluestacks is possible. For example, [see this StackOverflow answer for code](https://stackoverflow.com/a/26687223/4715679).

Cliclick, on the other hand, uses `CGEventPost()`, which Bluestacks seems to fail to recognize – but which is _not_ deprecated.

So, if you are still after a solution, you could download cliclick’s code, and try to replace the `CGEventPost` calls with appropriate `CGPostMouseEvent` calls `Actions/ClickAction.m`. Maybe this will work.
