### ISSUE TITLE
improved dragging

### ISSUE THREAD

**Issue by ccc-tomr** [BlueM/cliclick#37]
First: cliclick is awesome! Congrats BlueM

The current dd and du commands work well when you try to drag an object from one place to another in an immediate action. But I could not find a way of having an ongoing dragging action, which is needed when using cliclick as a component in a remote desktop software (a la RDP or VNC) 

Examples:
- a user is dragging a document across the desktop 
- interacting with a 3D Software and rotating/handling objects continuously 
- dragging scrollbar on a window

I could not find a way to do it (possible I just didn't find a existing way), so I took cliclick's code and adjusted actions for dd, du and mm. Happy to share and create a pull request but I couldn't create a separate branch in order to actually create a pull request. BlueM, let me know what I should do, I would love to contribute.

**Comment by BlueM** [comment]
There are only few committers and low commit frequency, therefore the project does not follow any specific branching approach. In other words: simply create a PR for `master`. Apart from that, I have to admit that I didn’t quite get yet what the problem is, but I guess seeing your code will help.

**Comment by monsterrandy** [comment]
I believe that this is the same issue that I'm reporting in my issue request:
#56.

Thomas –if you still have your code fix available, I would certainly be interested  in seeing it.
Thanks!
-rem

**Comment by ccc-tomr** [comment]
Hey rem,

Further below is my patch file, be aware that this patch goes on top of commit '0e0f40050c84c553c3f9876d77f5f8ff2467ab9e' (   Support reading commands from stdin (fixes #33) ), not on top the latest master. 

What I did is demote the 'dd' and 'du' command to mousebutton down/up only and extended MouseBaseAction to have an active drag mode. I am not sure how well it fits with Carsten's latest changes but it has worked for me very well, I use it almost on daily base with many different applications without problems.

I have a local PR but failed to push it into cliclick's repo. 

I typically don't post patch files but in this case it's pretty short. When I have time, I will try to create a PR based on the latest master.

Good luck 

diff --git a/Actions/DragUpAction.m b/Actions/DragUpAction.m
index 0aeb5c0..2f45d4d 100644
--- a/Actions/DragUpAction.m
+++ b/Actions/DragUpAction.m
@@ -50,19 +50,11 @@
 }
 
 -(void)performActionAtPoint:(CGPoint) p {
-    // Left button dragged
-    CGEventRef leftDragged = CGEventCreateMouseEvent(NULL, kCGEventLeftMouseDragged, CGPointMake(p.x, p.y), kCGMouseButtonLeft);
-    CGEventPost(kCGHIDEventTap, leftDragged);
-    CFRelease(leftDragged);
-
-    usleep(200000); // Some target applications require this to recognize the drop
     
     // Left button up
     CGEventRef leftUp = CGEventCreateMouseEvent(NULL, kCGEventLeftMouseUp, CGPointMake(p.x, p.y), kCGMouseButtonLeft);
     CGEventPost(kCGHIDEventTap, leftUp);
     CFRelease(leftUp);
-
-    usleep(800000); // This delay should usually prevent that a subsequent "wait" command is necessary
 }
 
 @end
diff --git a/Actions/MouseBaseAction.m b/Actions/MouseBaseAction.m
index e2cb96e..27d072e 100644
--- a/Actions/MouseBaseAction.m
+++ b/Actions/MouseBaseAction.m
@@ -124,11 +124,23 @@
         return;
     }
 
-    // Move
-    CGEventRef move = CGEventCreateMouseEvent(NULL, kCGEventMouseMoved, CGPointMake(p.x, p.y), kCGMouseButtonLeft); // kCGMouseButtonLeft is ignored
-    CGEventPost(kCGHIDEventTap, move);
-    CFRelease(move);
-    
+    // check if any mouse buttons are pressed 
+    NSUInteger mbutton = [ NSEvent pressedMouseButtons];
+    printf("mbutton = %lu \n", mbutton);
+
+    if( mbutton ){
+        CGEventRef dragmove = CGEventCreateMouseEvent(NULL, kCGEventLeftMouseDragged, CGPointMake(p.x, p.y), kCGMouseButtonLeft); // kCGMouseButtonLeft is ignored
+        CGEventPost(kCGHIDEventTap, dragmove);
+        CFRelease(dragmove); 
+    }
+    else
+    {
+        // Move
+        CGEventRef move = CGEventCreateMouseEvent(NULL, kCGEventMouseMoved, CGPointMake(p.x, p.y), kCGMouseButtonLeft); // kCGMouseButtonLeft is ignored
+        CGEventPost(kCGHIDEventTap, move);  
+        CFRelease(move);      
+    }
+
     [self performActionAtPoint:p];
 }
