### ISSUE TITLE
How to do cmd-C, cmd-V, cmd-X ...

### ISSUE THREAD

**Issue by ccc-tomr** [BlueM/cliclick#38]
How can you generate keyboard sequences like Copy, Paste etc. ?
I tried 'cliclick kd:cmd t:v ku:cmd' but that just prints out v instead of triggering a copying event.
If this isn't possible yet, I am happy to add something along the line of:
- ad:<key-code>, trigger key down event for <key-code> key
- au:<key-code>, trigger key up event for <key-code> key

or extend kd, ku to take a key code in addition to the current special keys

Any feedback would be helpful

**Comment by BlueM** [comment]
The solution you tried is correct – it’s a timing issue. When adding a delay, it works (at least it does on the Mac I am using):

    cliclick w:100 kd:cmd t:v ku:cmd

As timing issues (i.e.: cliclick is too fast) is a frequent cause of failure, I will close this issue, but open another one which will refer to this one and use this as a testcase.

**Comment by BlueM** [comment]
Well it’s early in the morning (at least in my part of the world), and I only now realize what’s strange about the above solution: I accidentally used `w:100` instead of `-w 100`. So it does work when waiting some time before emitting the first “key down” command. This is something which has to be investigated further.

**Comment by BlueM** [comment]
After **only** 1,5 years I took another look at this issue, and it indeed looks like a timing issue – but not a problem of a too fast succession of commands, but of a too fast first command. For instance, when I performed a `c` before the `kd`, it worked, but it didn’t without. The funny thing is that this did not work (in Terminal):

    cliclick kd:cmd t:v ku:cmd

… while this worked:

    sleep 1 && cliclick kd:cmd t:v ku:cmd

Which looks like the Return key which I use to send the current line of Terminal commands is still lurking around somehow. Strange. I experimented with the time cliclick waits before sending key events and an initial waiting time, and above a certain time (which is still neglectable for human perception), the problem disappeared.

To make a long story short: could you try https://www.bluem.net/files/cliclick/cliclick-4b3.1.dmg and let me know if it works for you?

**Comment by BlueM** [comment]
Fixed via 44dcc37 (accidentally mentioned #39 instead of #38 in the commit message) and now available in cliclick 4.0.

**Comment by focusaurus** [comment]
I'm having a similar strange issue trying to get cliclick to do a paste keyboard shortcut. I have 2 scenarios:

1. In a terminal, do `sleep 5; cliclick kd:cmd t:v ku:cmd`. During the sleep, bring TextEdit to the foreground. This works and it pastes the clipboard into TextEdit. I don't seem to need `-w 100` and it seems to work consistently.
2. If I trigger a script containing those commands via a hammerspoon keyboard shortcut, the code runs but the cliclick consistently has no effect.

I'm unclear how to troubleshoot further. @BlueM any suggestions? And thanks for a super handy tool!

**Comment by BlueM** [comment]
@focusaurus: sorry, I don’t use Hammerspoon and hardly know anything about it, therefore I can’t help.
