### ISSUE TITLE
How can I make cliclick type text into an application?

### ISSUE THREAD

**Issue by metmajer** [BlueM/cliclick#44]
Hi, not an issue, but an important question: I want to use cliclick to insert text into Sublime. How would I accomplish this? Thanks!

**Comment by BlueM** [comment]
Basically, if you want to type something, use the `t` (“type”) command. If you want to combine that with code that ensures that Sublime is the frontmost application, a typical method would be to use AppleScript like this:

```applescript
tell application "Sublime Text" to activate
do shell script "/usr/local/bin/cliclick w:200 t:'The text to type'"
```

Equally, you can also use the `cliclick` invocation directly in a shell script (or a shell one-liner) and instead execute the AppleScript `activate` by using `osascript`:

```applescript
osascript -e 'tell application "Sublime Text" to activate' && cliclick w:100 t:'The text to type'
```

NB: The `w` (“wait”) command is used here to give Sublime some time to become frontmost app.
