### ISSUE TITLE
Feature Request: Record

### ISSUE THREAD

**Issue by jnovack** [BlueM/cliclick#51]
Add a `--record SECONDS` option.

I want to record a set of movements (minimum, just X/Y coordinates) with timings for a set number of seconds.

I have a use case where I need the mouse to follow a specific path, currently, am doing `while true; do ./cliclick p >> output.txt; done`, and regexing the output.

Unfortunately, there are lots of duplicates during pauses but mostly because I don't know the ms between the pauses or the polling interval since I'm running command-line (re-running the command obviously causes some ms delay, as well as writing to a file).  There's no control.  I don't know if it's 10ms or 20ms that I've stayed in a certain spot.

A record function could remove duplicate `m:x,y` positions, and insert in proper `w:ms` commands.

EDIT: sorry, I derped.  `./cliclick` actually clicked Close. ;)

**Comment by BlueM** [comment]
As this is a pretty specific requirement / usage scenario, I’m not convinced that it really should be implemented as part of cliclick.

However, there are (at least) two things you could try to get the information you need_

**Option 1:**  It’s pretty easy to listen to global mouse events in Cocoa. You can simply launch Xcode, create a new project (Cocoa application / Objective-C – with all default settings), and in `applicationDidFinishLaunching` inside the auto-generated file `AppDelegate.m`, you add these lines:

```
[NSEvent addGlobalMonitorForEventsMatchingMask:NSEventMaskMouseMoved handler:^(NSEvent *event) {
    NSLog(@"%@", [event description]);
}];
```

As soon as you run the application, it will write any mouse movement events with precise timing info to Xcode’s log. (And, of course, it’s possible to customize this output to precisely fit your needs.)

**Option 2:** Clone the codebase and change https://github.com/BlueM/cliclick/blob/master/Actions/PrintAction.m#L58 to something like this:

```
printf("Current mouse position: %.0f,%.0f // %f\n", point.x, point.y, ([NSDate timeIntervalSinceReferenceDate] * 1000));
```

Plus, wrap this in loop (for instance, see `nanosleep` elsewhere in the code) or `NSTimer` (lots of examples on the web).
Then, compile cliclick using Xcode or `make`, invoke it and you get the milliseconds, which is way easier for finding relative times.
