### ISSUE TITLE
Screenshot shortcut

### ISSUE THREAD

**Issue by bhem** [BlueM/cliclick#52]
Hello,

I'm looking for a method to emulate shift + cmd + 3 (screenshot)

I tried this

    cliclick kd:shift,cmd kp:num-3

but it doesn't work.

Any help will be very nice

**Comment by BlueM** [comment]
For taking screenshots, there’s `/usr/sbin/screencapture`, which has been part of OS X since 10.2, and therefore is a much better alternative than using `cliclick`, as you don’t have to rely on additional software.

**Comment by bhem** [comment]
Thanks for this tip
