### ISSUE TITLE
Minimisation/hiding of all other program windows when performing cliclick actions?

### ISSUE THREAD

**Issue by emg80** [BlueM/cliclick#53]
When triggering cliclick to perform actions, all other windows/programs are being minimised/hidden?

El Capitan 10.11.1

**Comment by BlueM** [comment]
Reading “are being minimised/hidden”, it sounds as if this is what is happening when you are using cliclick. But I’m pretty sure that this cannot happen. So is this a feature request and you would like to hide everything?

**Comment by emg80** [comment]
I was using another application to call cliclick and that is where the problem was. Sorry! Please close this issue. (as there is no issue with cliclick!)
