### ISSUE TITLE
Can't compile from source ActionsClassesMacro.h not found

### ISSUE THREAD

**Issue by scarrico** [BlueM/cliclick#54]
I believe this is due to a new version of the OS and/or XCode.

OS version: 10.12.4
XCode Version: 8.3.2

Here's the build:
sandra@MacBook-Pro-2:~/socrates/snapshots/bin/cliclick-master$ make install
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/ClickAction.o Actions/ClickAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/ColorPickerAction.o Actions/ColorPickerAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/DoubleclickAction.o Actions/DoubleclickAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/DragDownAction.o Actions/DragDownAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/DragUpAction.o Actions/DragUpAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/KeyBaseAction.o Actions/KeyBaseAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/KeyDownAction.o Actions/KeyDownAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/KeyDownUpBaseAction.o Actions/KeyDownUpBaseAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/KeyPressAction.o Actions/KeyPressAction.m
Actions/KeyPressAction.m:136:51: warning: 'NSSystemDefined' is deprecated: first deprecated in macOS 10.12
      [-Wdeprecated-declarations]
        NSEvent *e1 = [NSEvent otherEventWithType:NSSystemDefined
                                                  ^~~~~~~~~~~~~~~
                                                  NSEventTypeSystemDefined
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:78:26: note: 
      'NSSystemDefined' has been explicitly marked deprecated here
static const NSEventType NSSystemDefined        API_DEPRECATED_WITH_REPLACEMENT("NSEventTypeSystemDefined", macosx(10....
                         ^
Actions/KeyPressAction.m:147:51: warning: 'NSSystemDefined' is deprecated: first deprecated in macOS 10.12
      [-Wdeprecated-declarations]
        NSEvent *e2 = [NSEvent otherEventWithType:NSSystemDefined
                                                  ^~~~~~~~~~~~~~~
                                                  NSEventTypeSystemDefined
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:78:26: note: 
      'NSSystemDefined' has been explicitly marked deprecated here
static const NSEventType NSSystemDefined        API_DEPRECATED_WITH_REPLACEMENT("NSEventTypeSystemDefined", macosx(10....
                         ^
2 warnings generated.
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/KeyUpAction.o Actions/KeyUpAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/MouseBaseAction.o Actions/MouseBaseAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/MoveAction.o Actions/MoveAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/PrintAction.o Actions/PrintAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/RightClickAction.o Actions/RightClickAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/TripleclickAction.o Actions/TripleclickAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/TypeAction.o Actions/TypeAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o Actions/WaitAction.o Actions/WaitAction.m
cc  -include cliclick_Prefix.pch -I Actions -I .   -c -o ActionExecutor.o ActionExecutor.m
ActionExecutor.m:30:10: fatal error: 'ActionClassesMacro.h' file not found
#include "ActionClassesMacro.h"
         ^
1 error generated.
make: *** [ActionExecutor.o] Error 1

**Comment by BlueM** [comment]
This was a Makefile problem when immediately running `make install` without a previous `make`. (And then, in the commit which fixed this, it was a problem of being too early in the morning, which resulted in me committing a temporary/testing target path, which I had to fix using a second commit …)
