### ISSUE TITLE
Window position does not change while being dragged using the dd/du commands

### ISSUE THREAD

**Issue by monsterrandy** [BlueM/cliclick#56]
I am using the start drag and end drag commands invoked as voice commands from Mac Dragon 6 so that I can drag windows and other UI elements around without having to hold the mouse button down. So, for example, I'll say the command "mouse down" (cliclick dd:+0,+0) to start the drag once my mouse is positioned over a window title bar, then I will move the window using my mouse, and then I will say the command "mouse up" (cliclick du:+0,+0) to end the drag.

All of this works, but the problem I'm having is that while the drag is in progress, the window is not being continuously dragged across the screen; only when I end the drag operation does the window position update. 

I'm seeing the same behavior when using this technique to drag objects within a drawing program like Sketch. Scrollbars in the Chrome browser do actively update during the drag, although scrollbars in the Finder do not.

Any ideas why the Mac would not update the position of an element while it is being dragged using these commands?

Thanks!
-rem

**Comment by BlueM** [comment]
Only after your comment on #37 I realized that I hadn’t understand your description correctly. Now that I have: have you already tried the code in branch `4.0-dev` (or just try https://www.bluem.net/en/news-and-beyond/cliclick-4-beta/)? It breaks down movements in a sequence of a large number of small movements.

**Comment by monsterrandy** [comment]
Thanks Carsten! I'm currently using version 3.3 and will download the beta to try it out.

One thing: from the description of the changes you've made in version 4, it sounds like this is a technique to move the mouse smoothly between M or DD/DU commands that occur one after another in a script. In my use case, I issue a DD command to start a drag , then I move the mouse using my pointing device (not under script control), and then I issue a DU command when I get to my destination.  It is during the time when I am moving the mouse using my pointing device that no visual updates occur  (i.e. if I am dragging a window, the window does not move during the drag; it only updates its position after the DU command is issued ). 

So I'm not sure if these changes will address my problem. But I will try the beta and report back to you.
Thanks so much!
-rem

**Comment by BlueM** [comment]
Closed due to no reaction after 6+ months. (And the problem can probably not fixed from within the cliclick codebase, anyway.)
