### ISSUE TITLE
Add support for ku at coordinates

### ISSUE THREAD

**Issue by jprokos** [BlueM/cliclick#58]
Some web pages/menus only recognize a click after releasing the mouse,,, a key up. 

Using `cliclick c` on a menu does not trigger the web page button. The only way to achieve a click on these menus is to use the `cliclick dc` option which seems to work. If a `ku` in combination with coordinates and not other keystrokes could be programmed into the software that would be helpful.

**Comment by BlueM** [comment]
`ku` is related to keys and has nothing to do with mouse actions, so I don’t quite see where it comes into play here.

But more important: it would be pretty helpful if you could provide URLs of 2 or 3 websites where you experienced problems using cliclick. (Including descriptions of what you tried to click.)

**Comment by jprokos** [comment]
I understand the way it's currently programmed, I was asking for new functionality. Like I said I was able to make it work using the `dc` command.

The site I used cliclick on was the Google Voice web site. Because Google only allows a user to delete call history one call at a time I used cliclick to do the mouse work for me. Thanks for that!

While in Google Voice looking at call history there is a vertical elipsis menu (options). If I click on it with my mouse and hold nothing happens, it's once I release the mouse that the menu activates. The same for it's sub-menu where the "Delete" option lives. Issuing the `c` command on these menus does not activate them either. Issuing the `dc` command does activate them. I am not versed in how the emulation works, so can't offer suggestions. I just assumed that a click was comprised of two "codes"; one for depressing and the other for releasing and that the second half of the clicking action was not represented by any option in cliclick.

I haven't tried cliclick on other websites. In regards to mouse behavior alone I also experienced this in Apple Mail. Clicking on a new email does nothing until I release the mouse. It's not highlighted by the depression of the mouse but the release. Clicking on items in the finder is different, they are selected as soon as I depress the mouse button.

**Comment by BlueM** [comment]
It is normal that browsers perform actions when releasing the mouse button, not when pushing the mouse button. (Example: try the buttons or links on this page.) And cliclick in this regard behaves just a real mouse: it sends a “button was pressed” event, then it sends a “button was released” event.

In your case: if doubleclicking works for you – fine. It sounds as if it should have worked with simple clicking, but simply by reading your description, it is hard to tell what is going on. Maybe cliclick is releasing the button too fast. If you happen to have a little Objective-C knowledge, it is pretty simple to try that out (hint: add `usleep()` call in `ClickAction.m`, you can find examples for that in other files).

But anyway, this has nothing to do with `ku`. In fact, as written above, cliclick does what you are asking for when performing a simple `c`, therefore there is nothing to add or change.
