### ISSUE TITLE
Click through AppleScript is not opening menu of system bar

### ISSUE THREAD

**Issue by francwalter** [BlueM/cliclick#64]
If I do a click through AppleScript on the system bar (where the clock, the battery, the wifi etc. are, in german "Menüleiste") nothing happens. My code (with AS):
`do shell script "/opt/local/bin/cliclick c:810,10"`
Not possible to emulate a click there. The mouse jumps to the position (810,10) but doesn't click.
With direct command on Terminal it is no problem.

Is there a trick or is it just forbidden by the system to use cliclick through AS?

On Mac OS 10.11.6 with cliclick (vs3.3, 11/12/2016) on my MacBook Pro Mid 2009

Thank

frank

**Comment by BlueM** [comment]
macOS does not even know if cliclick was invoked through AppleScript or from the shell – technically, it’s the same.

And you will see that AppleScript is not the problem when running AppleScript code from the Shell which in turn runs shell code:

     osascript -e 'do shell script "/usr/local/bin/cliclick c:1116,9"'

However, what I can reproduce is when running the `do shell script` line from within Script Editor, it seems that nothing happens. For whatever reason, the Script Editor seems to swallow the first event. So, as usual when encountering issues like these with cliclick, you can simply try to perform another click, which works on my Mac:

    do shell script "/opt/local/bin/cliclick c:810,10 c:."

(You might need a “wait” command – `w:50` or so – between the `c` commands.)

**Comment by francwalter** [comment]
Thank a lot for the quick reply.
I just don't use AS and it works as shellscript perfectly 👍
