### ISSUE TITLE
How can reach this app from python?

### ISSUE THREAD

**Issue by schroef** [BlueM/cliclick#65]
Im not that good at coding and now really just a bit. I got this python script for blender which copies the mouse movent in blender to something in Marvelouse Designer. Now this code was written for windows, which can use:

`ctypes.windll.user32.mouse_event(2, 0, 0, 0,0) # left down`

is there a easy way to do this with for example Popen orso? But i need to now how to get the path or should i look elsewhere?

**Comment by schroef** [comment]
Okay i got it to work :) Im using this as the code now. 

`os.system('/usr/local/bin/cliclick c:'+ str(x) +','+str(y))`

Holy moly this is damn beautiful. Now i can draw the garnments in illustrator convert them to mesh and import that mesh in Blender, then use blender to draw it automatically in Marvelous Designer.
Ill post a short video of this later.

Just wanted to say... many thanks for this great little app!!!

**Comment by schroef** [comment]
Hi man, here's what i got working using your nice little app. Its so cool :)

https://www.dropbox.com/s/qb0ddoixuah0fm7/Pattern_generator_md.gif?raw=1

**Comment by BlueM** [comment]
Looks like a straight-forward Python approach.

Regarding your use-case: I keep being surprised for what kinds of tasks cliclick is used ;-)
