### ISSUE TITLE
Mouse moves slow in 4.0b1

### ISSUE THREAD

**Issue by francwalter** [BlueM/cliclick#67]
Hallo

I just updated to cliclick 4.0b1 from version 3.3 and now I notice that when I do mouse moves the Mouse Cursor doesn't jump anymore, but moves visible from a to b. It moves as if I would use the mouse myself, even slower.
Is this by purpose or intention?
Or is it a setting? 
Is it related to my own compiling with XCode and kind of home-made? I set Product > Build For > Running though.

I reverted to 3.3 where it is fast again.

Thanks
frank

**Comment by BlueM** [comment]
See https://www.bluem.net/en/news-and-beyond/cliclick-4-beta-2-released/

**Comment by francwalter** [comment]
Thank!

**Comment by francwalter** [comment]
The new -e feature is indeed useful, to have switched it off as default is the right thing. I already use it in a command which wouldn't work if it is fast done: 
DVD-Player, show the menu bar by moving the mouse up. No way to do that fast, only with the -e 200 it worked :) 
Thank.
