### ISSUE TITLE
Left clicks turn into right ones with palm on trackpad

### ISSUE THREAD

**Issue by sirdavidoff** [BlueM/cliclick#68]
Great tool – many thanks for writing this!

I'm triggering clicks using keyboard shortcuts, and quite often a part of my palm is on the trackpad when I do so. When this happens the click becomes a right click rather than a left one.

Is there any way to prevent this, short of changing the way that trackpad right clicks work in `System Preferences`?

**Comment by BlueM** [comment]
Not to my knowledge. The behavior you get is the sum of what cliclick does and what your palm does (via the trackpad). To prevent this, the trackpad events (probably a series of events) would have to be “swallowed”. Maybe there is a way to do that, but I simply don’t know.
