### ISSUE TITLE
mouse right-click - Unrecognized action shortcut

### ISSUE THREAD

**Issue by okramovic** [BlueM/cliclick#72]
Hi,

when I use command 'rc' for right click (example:  cliclick rc:100,100 ), I get error:
     Unrecognized action shortcut “rc” in “rc:100,100”

Any idea why that might be happening or how it can be fixed?
I'm using Yosemite 10.10.5 if that is important anyhow.

**Comment by BlueM** [comment]
Which cliclick version?

**Comment by BlueM** [comment]
Then the error you get is the expected behaviour, as `rc` is not yet available in 3.3. For the time being, you can use a beta of cliclick 4 (https://www.bluem.net/en/news-and-beyond/cliclick-4-beta-3-released/).

**Comment by okramovic** [comment]
okay, thanks for info!
