### ISSUE TITLE
Key combo not working after V4.0 upgrade

### ISSUE THREAD

**Issue by ghost** [BlueM/cliclick#74]
Let's say I want to simulate `cmd + option + f` key combo, previously it was working when I use `cliclick kd:cmd,alt t:f ku:cmd,alt`. But after the V4.0 upgrade, this doesn't work anymore. 

What's the proper way to achieve that key combo instead?

**Comment by BlueM** [comment]
The command is correct – this is a bug in cliclick, introduced by me shortly before the 4.0 release while fixing another misbehavior.

Could you try https://www.bluem.net/files/cliclick/cliclick-4.0.1.dmg and let me know if it fixes the problem?

**Comment by rx2130** [comment]
It works! 

FYI I only test its very basic usages.
