### ISSUE TITLE
Improvement suggestion:  Mouse position when negative (screen to the left of main)

### ISSUE THREAD

**Issue by wolfiex** [BlueM/cliclick#75]
> ./cliclick/cliclick c:-100,-100 

Although the extension of a screen to the right of the main monitor works great, If you wish to access a position left it results in a negative number. The above command only shifts the cursor -100 pixels from its current position rather than moving it left of the main screen by 100. 

A solution within my code is to read the current cursor position, and subtract this from the desired, but a neater solution would involve that code being within the cliclick program.

**Comment by BlueM** [comment]
Quote from the Readme (or `cliclick -h`’s output):

> If you need to specify absolute negative values in case you have a setup with a second display arranged to the left of your main display, prefix the number with “=”, for instance “c:100,=-200”
