### ISSUE TITLE
can't drag and drop

### ISSUE THREAD

**Issue by shinriyo** [BlueM/cliclick#78]
Hello
I wanna use it for QuickTime recoeding scxreen capture.

I want drag like drawing square (from left-up to right down).

If I create 640x360 square.
I guess it is like below
```
cliclick dd:300,200; cliclick du:940,560
```
but, it can't success to drag and drop...

**Comment by BlueM** [comment]
Try it in one call:

    cliclick dd:300,200 du:940,560

If that doesn’t work, try to slow it down by adding a `w` (“wait”) command between the existing commands, for example `w:100` for waiting 100 milliseconds.

**Comment by BlueM** [comment]
Closed, as no feedback in over two months.

**Comment by alin89c** [comment]
Thanks for the tip, BlueM!
