### ISSUE TITLE
cliclick 4 on OS X < 10.9

### ISSUE THREAD

**Issue by ryandesign** [BlueM/cliclick#81]
For cliclick 4, the minimum supported OS X version is 10.9. However, it builds for me and seems to work on Mac OS X 10.7. Are there any known issues on 10.7 or 10.8?

**Comment by BlueM** [comment]
No, I’m not aware of any issues. Declaring 10.9 as minimum for cliclick 4.0 was an arbitrary decision, with the purpose of preventing BC breaks caused by future 4.* versions which actually might need 10.9 features.
