### ISSUE TITLE
Single click stuck mouse down

### ISSUE THREAD

**Issue by nirarad** [BlueM/cliclick#82]
Recently we noticed that while using mouse clicks,
On every 2nd click, the mouse seems to be stack on ‘press down’ state,
Meaning that while trying to move to the 3rd click position,
We get a ‘mouse drag’, which moves an object that was clicked on the 2nd click.
Cliclick is triggered as a single command, with about 1-2 seconds delay between calls.

We are using Cliclick V.4.0.1.
Example command:
`cliclick c:791,67`

**Comment by BlueM** [comment]
I tried to reproduce this behavior, but didn’t succeed, both with a single invocation and a series of invocations:

    cliclick -w 1500 c:230,554 c:229,590 c:228,706
    cliclick c:230,554 w:1500; cliclick c:229,590 w:1500; cliclick c:228,706

Both behaved as expected, i.e.: 3 distinct clicks, no dragging.

What are the exact calls to `cliclick` in your case? And what is the target application which is in the foreground when this behavior can be observed?

**Comment by nirarad** [comment]
We currently stopped using this utility due to this bug.
We have replaced it with a python module that simulates mouse clicks on mac.
Let me know if you managed to solve the issue in the future.

**Comment by BlueM** [comment]
As I cannot reproduce it and don’t have any further information, there is nothing to solve.
