### ISSUE TITLE
Mojave 10.14 support

### ISSUE THREAD

**Issue by apximax** [BlueM/cliclick#83]
It totally doesn't work on Mojave 10.14.
I tried to build it (sudo make install), build process was successful, but the result was the same as when I just install cliclick using homebrew or downloading from the site.

When I try some command I see typical message (verbose mode), but nothing happens.

**Comment by BlueM** [comment]
What exactly is the command(s) you have tried?

**Comment by apximax** [comment]
Tried to use next script:
```
#!/bin/bash

sleep 5

while [ : ]
do
  NUMBER=$[ ( $RANDOM % 5 ) + 0 ]
  sleep $NUMBER

  cliclick -m verbose kd:ctrl
  for i in `seq 1 $[ ( $RANDOM % 10 ) + 1 ]`
  do
    cliclick -m verbose kp:tab
  done
  cliclick -m verbose ku:ctrl

  for i in `seq 1 $[ ( $RANDOM % 5 ) + 0 ]`
  do
    cliclick -m verbose kp:page-up
  done

  for i in `seq 1 $[ ( $RANDOM % 5 ) + 0 ]`
  do
    cliclick -m verbose kp:page-down
  done

done
```
Output:
![image](https://user-images.githubusercontent.com/17577935/43834294-492ff9c4-9b16-11e8-98f9-2a445cf484ca.png)

Also tried something like
```
cliclick -m verbose m:1370,70
cliclick -m verbose c:1370,70
etc
```
The script above had worked before I updated mac os from high sierra to mojave.

Maybe it will be helpful:
When I faced this problem then I tried to find some similar tool. I didn't find anything that allows me emulate keyboard events. But I just tested [MouseTools](http://www.hamsoftengineering.com/codeSharing/MouseTools/MouseTools.html) and it doesn't work for me too...

Unfortunately I have nobody else who could test these tools on mac os mojave.

**Comment by apximax** [comment]
@BlueM Sorry, my bad
The cause was not in the cliclick utility

**Comment by klysdale** [comment]
Was there resolution to this case?  I use cliclick as well and it doesn't respond at all now on Mojave.  Just looking to see if there is a fix yet on Mojave.  Thanks,

**Comment by BlueM** [comment]
If you have problems with cliclick on Mojave, make sure you have granted full disk access to Terminal (or iTerm) in the security section of the system preferences.

**Comment by klysdale** [comment]
Thanks.  I have added Terminal to Full Disk Access but it didn't change anything.  Terminal was restarted as well.  
![screen shot 2018-11-01 at 1 57 46 pm](https://user-images.githubusercontent.com/33916998/47873295-d329a480-ddde-11e8-9595-42d2e221dc3a.png)

**Comment by BlueM** [comment]
I’m sorry, but then I have no idea. I haven’t experienced any misbehavior on Mojave myself, and a user who mailed me because cliclick appeared to do nothing was able to fix this by granting Full Disk Access. I don’t know of any other causes.

**Comment by apximax** [comment]
@klysdale For me now it works without full disk access to Terminal, I just granted Accessibility rights to Terminal and it is enough...

**Comment by klysdale** [comment]
@apximax, Thank you.  Granting accessibility rights worked.

**Comment by sachinhr10** [comment]
<img width="420" alt="Screenshot 2019-07-29 at 3 08 38 PM" src="https://user-images.githubusercontent.com/31371035/62041733-fa03f280-b219-11e9-9701-ef9822dd5138.png">

getting this message when trying to run test on a mac Catalina machine (10.15 beta)

Tried giving full drive access to terminal. Still getting the same message.
Also cliclick option isn't visible in the access grant list.
