### ISSUE TITLE
Mouse Down vs dd

### ISSUE THREAD

**Issue by whimsica** [BlueM/cliclick#85]
I'm trying to use cliclick to do a mouse down event on excel. dd does not seem to duplicate the behavior as a mousedown.  Is there a way to do just mousedown and mouseup?

**Comment by BlueM** [comment]
Well … I’d say that sounds just like a click. But I assume you have thought of that yourself.

**Comment by whimsica** [comment]
I just need the mousedown without the mouseup. Is that possible?

**Comment by BlueM** [comment]
Technically this would be possible (these are 2 different events), but I would not see the use case, as sooner or later the mousebutton would have to be released.

If you think, this really solves a problem for you, test it by commenting or removing lines https://github.com/BlueM/cliclick/blob/master/Actions/ClickAction.m#L63-L65 and compile it for yourself.

**Comment by BlueM** [comment]
Closed, as no reaction within two years
