### ISSUE TITLE
Can't get cliclick to work

### ISSUE THREAD

**Issue by KKPMW** [BlueM/cliclick#86]
Hello,

Not sure if this is an issue or rather a question - but I cannot get cliclick to work.

1. When I type `cliclick t:word` in terminal - nothing happens
2. Tried `open -a "Rstudio" && cliclick w:1000 t:word` - Rstudio opened, but nothing else happened.

In both cases I got no errors. But also no action. I tried to install cliclick from macports as well as compiled the one on this repository (using make).

Maybe there is something I missed? Should `cliclick t:word` print "word" in terminal? If not - what is the easiest way to make sure the version I have is working correctly?

**Comment by BlueM** [comment]
I you are running 10.14 (Mojave) and a `which cliclick`yields the path to which you installed it, you probably need to enable full disk access for Terminal in the system preferences.

**Comment by KKPMW** [comment]
@BlueM Thank you for the tip. Full Disk Access was granted to Terminal, but in addition I had to allow it to "control the computer". It is working now.
