### ISSUE TITLE
Get Mouse Position at Click

### ISSUE THREAD

**Issue by chipbeaulieu** [BlueM/cliclick#90]
I am looking for a CL tool that will return the mouse coordinates after I click the mouse. This would be used when I can see where I want to take a screen shot, but it changes regularly. So I would run cliclick, it would capture the mouse so I can move it anywhere and then return the coordinates of where I click. I would run it a 2nd time to get the bounding rectangle and then I would know the exact coordinates to take a screen shot. Most of the tools I look at assume you know where you want the mouse to go.

**Comment by BlueM** [comment]
For this precise use case, cliclick is not the right tool. But if you don’t insist on getting the coordinates automatically upon click, but manually by invoking cliclick at the shell, you can use it like this:

1. Open a Terminal window
2. Bring the desired application to the front and move the mouse whereever you’d like to click.
3. Now, _instead_ of clicking, simply cmd-tab to Terminal (i.e.: _don’t use the mouse for changing the application_) and execute `cliclick p` – or probably better: `cliclick p | pbcopy`, to directly copy the coordinates. Paste the coordinates wherever you need them.
4. Repeat again starting from step 2. as often as needed.
