### ISSUE TITLE
Are the events detectable by other softwares?

### ISSUE THREAD

**Issue by eddiemf** [BlueM/cliclick#93]
Hello there, 

I'm planning to use this tool as a simple macro in a game protected by BattleEye, so I'm wondering how detectable are the input events created by it.

I know in windows it's kinda impossible to create an undetectable macro since all events are sent via the windows API which most shields (like BattleEye) can easily hook into and detect if the event was faked or made by real hardware. But I've heard that in Unix based systems it's different, though I have no idea how it works.

Do you have any information on that?

Thanks a lot!

**Comment by BlueM** [comment]
In newer versions of macOS, you have to give cliclick (or Terminal, I don’t remember exactly) permission to use assistive devices in the System Preferences, therefore it is obvious that for the OS, synthetic / programmatic events must somehow be different from real events. But I don’t know (but would rather doubt it) if on the application-level a programmatic event can be identified.

**Comment by eddiemf** [comment]
Thanks for the quick reply!

Can you tell me a bit about the API you're using to create these events? I checked the source code but I have no experience at all with Objective-C or MacOS programming. Is it some kind of API that you can simply use from XCode or something like that? Can you provide name/docs for it? With that information I hope to make some more research in other places to know for sure if it's somehow detectable or not by any kind of third party software.

Thanks a lot again!

**Comment by BlueM** [comment]
Yes, cliclick only uses official APIs – which one, depends on the type of action. For instance, for moving the mouse or clicking, it’s `CGEventCreateMouseEvent()`, see https://github.com/BlueM/cliclick/blob/master/Actions/MouseBaseAction.m#L138
https://github.com/BlueM/cliclick/blob/master/Actions/ClickAction.m#L56

**Comment by eddiemf** [comment]
Awesome, thank you very much for all the info!
