### ISSUE TITLE
Issue on Catalina Beta!

### ISSUE THREAD

**Issue by gcpmusic** [BlueM/cliclick#94]
On latest Catalina Beta the example doesnt work:

cliclick c:28,11 w:500 m:+0,+24 w:1000 kd:alt w:1000 c:. ku:alt

Any advice. THX in advance.

**Comment by BlueM** [comment]
Unable to reproduce this problem on a non-beta Catalina. Either this was related to the beta, or – if you can still observe it with a non-beta installation – it might be that Terminal is lacking permissions to do certain things (see Security preference pane).
